### ISSUE TITLE
Installation Error.

### ISSUE THREAD

**Issue by ghost** [dsisco11/SR_Plugin_Loader#37]
INFO: Installing: Sisco's Plugin Loader v0.7.5
INFO: Checking Assembly...
WARN: Detected external assembly file changes, a complete purge and reinstall of all required files will now take place.
INFO: Steam will reinstall Assembly-CSharp.dll
INFO: Starting GCV
INFO: Steam Validation Started...
...
INFO: Awaiting assembly release...
INFO: Assembly-CSharp.dll HASH:  d11bd943179b59b65d013e9958698c1bda5075e3
INFO: Creating backup: c:\program files (x86)\steam\SteamApps\common\Slime Rancher\SlimeRancher_Data\Managed\Assembly-CSharp.dll

ERROR: Exception has been thrown by the target of an invocation. Object reference not set to an instance of an object.
Stack Trace:    at Logging.Logger._OutputLine(LogLevel level, String moduleName, String format, Object[] args) in C:\CODE\GAME_MODS\SR_Plugin_Loader\SR_Plugin_Loader\Logging\Logger.cs:line 121
   at SR_PluginLoader_Installer.Program.Do_Variable_Changes(ModuleDefinition& dll)
   at SR_PluginLoader_Installer.Program.Modify_Assembly_DLL(ModuleDefinition dll)
   at SR_PluginLoader_Installer.Program.Run_Program()

Outter Stack Trace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Main(String[] )
Press ANY key to exit

**Comment by jimmon89** [comment]
i have the same error
fresh install of slime rancher, on windows 10 64 bit.
[installer.log.txt](https://github.com/dsisco11/SR_Plugin_Loader/files/517858/installer.log.txt)

**Comment by dylanrenwick** [comment]
The current released installer is for a much older version of Slime Rancher (summer 2016). The rewrite will fix these issues and update the plugin loader to work with current versions of the game.
