### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by ghost** [dsisco11/SR_Plugin_Loader#38]
WARN: Sorry, we're unable to find your slimerancher install directory.
WARN: Please enter the path to your SlimeRancher's '.exe' file, or drag it's folder to this window and then hit <enter>.
"E:\STEAM\steamapps\common\Slime Rancher"
INFO: Installing: Sisco's Plugin Loader v0.7.5
INFO: Checking Assembly...
ERROR: Exception has been thrown by the target of an invocation. Object reference not set to an instance of an object.
Stack Trace:    at Logging.Logger._OutputLine(LogLevel level, String moduleName, String format, Object[] args)
   at SR_PluginLoader_Installer.Program.Do_Variable_Changes(ModuleDefinition& dll)
   at SR_PluginLoader_Installer.Program.Modify_Assembly_DLL(ModuleDefinition dll)
   at SR_PluginLoader_Installer.Program.Run_Program()

Outter Stack Trace:    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Main(String[] )
Press ANY key to exit

**Comment by dylanrenwick** [comment]
The current released installer is for a much older version of Slime Rancher (summer 2016). The rewrite will fix these issues and update the plugin loader to work with current versions of the game.
